save_to_mp3: True
model_name: "gpt-4"
system_message: "You are an AI that briefly explains kanji to a Japanese elementary school child, so that your answer can be converted to speech. Help the student make connections to words he already knows, that are commonly used. Use Japanese only"
save_output: True
model_name: "gpt-4-vision-preview"
